login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('', views.login, name='login'),    
    # url('logoutfun', views.logoutfun, name='logoutfun'),
]

reassessment/urls.py
from django.conf.urls import url
from django.urls import path, include 
from . import views

urlpatterns = [
    path('view_request', views.reassessment_request, name='view_reassessment_request'),
    path('list', views.reassessment_approved, name='reassessment_approved'),    
    path('list/<int:id>/update', views.reassessment_update, name='reassessment_approved_id'), 

    path('home', views.reassessment_home, name='reassessment_home'),
    path('update_marks/course/<int:course_id>', views.update_reassessment_marks, name='reassessment_update_marks'),   
    path('update_attendance', views.reassessment_attendance_list, name='reassessment_update_attendance'), 
    path('<int:id>/update', views.reassessment_attendance_update, name='reassessment_attendance_update'),   
]  

student_portal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.shortcuts import redirect
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

from login import views

urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('login/', include('login.urls'), name='signin'),
                  path('logout/', views.logoutfun, name='logoutfun'),
                  path('dashboard/', include('dashboard.urls')),
                  path('register/', include('register.urls')),
                  path('college/', include('college.urls')),
                  path('programmes/', include('programme.urls')),
                  path('course/', include('course.urls')),
                  path('accomodation/', include('accomodation.urls')),
                  path('hostel/', include('hostel.urls')),
                  path('migration/', include('migration.urls')),
                  path('feetransaction/', include('fee_transaction.urls')),
                  path('convocation_registration/', include('convocation_registration.urls')),
                  path('students/', include('student.urls')),
                  path('fee_request/', include('fee_request.urls')),
                  path('', lambda request: redirect('login/', permanent=True)),
                  path('fee-structure/', include('fee_structure.urls')),
                  path('migration/', include('migration.urls')),
                  path('convocation-registration/', include('convocation_registration.urls')),
                  path('student-profile/', include('each_student_portal.urls')),
                  path('faculty/', include('faculty.urls')),
                  path('exam-appear/', include('exam_appear.urls')),
                  path('exam-registration/', include('exam_registration.urls')),
                  path('exam-timetable/', include('exam_timetable.urls')),
                  path('results/', include('results.urls')),
                  path('marksheet/', include('marksheet.urls')),
                  path('recheck/', include('recheck.urls')),
                  path('backlog/', include('backlog.urls')),
                  path('reassessment/', include('reassessment.urls')),
                  url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
                  url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(),
                      name='password_reset_done'),
                  url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
                  url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('change-password', views.change_password, name='change_password'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reassessment/models.py
from django.db import models
from course.models import Course
from student.models import Student
from django.core.validators import MinValueValidator
from decimal import Decimal
from exam_appear.models import appearance
# Create your models here.
   
class reassessmentfee(models.Model):
    receipt_no = models.CharField(max_length=100)
    payment_mode = models.CharField(max_length=30)
    transaction_id = models.CharField(max_length=30,blank=True)
    cheque_no = models.CharField(max_length=30, default=None)
    payment_date = models.DateTimeField()
    payment_proof = models.FileField(upload_to='fees_proof',null=True)
    amount =  models.DecimalField(decimal_places=2, default=0,max_digits=12, validators=[MinValueValidator(Decimal('0.00'))],blank=True, verbose_name='Other Charges')    
    approved = models.BooleanField(null=True)
    remarks = models.CharField(max_length=50, default=None, null=True)
    courseid = models.CharField(max_length=50, default="")
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
  
class reassessmentteacher(models.Model): 
    seatno = models.ForeignKey(appearance, on_delete=models.CASCADE)
    courseid = models.ForeignKey(Course, on_delete=models.CASCADE)
    attendance = models.BooleanField(null=True)    
    marks = models.CharField(max_length=3)
    pass_fail = models.BooleanField(null=True)
    status = models.BooleanField(null=True)

reassessment/forms.py
from django import forms
from django.contrib import auth
from django.forms import ModelForm
from .models import reassessmentfee , reassessmentteacher
from student.models import Student
from course.models import Course
from django.shortcuts import get_object_or_404

class reassessment_fee_form(forms.Form):
    CHOICES = (('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online Payment', 'Online Payment'))

    receipt_no = forms.CharField(required=True, label='Receipt Number *', max_length=100, widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': 'Receipt Number'}))
    payment_mode = forms.ChoiceField(choices=CHOICES, label='Payment Mode *',
                                     widget=forms.Select(attrs={'class': "form-control"}))
    transaction_id = forms.CharField(required=False, label='Transaction ID', widget=forms.TextInput(
        attrs={'class': "form-control", 'placeholder': 'Transaction ID'}))
    cheque_no = forms.CharField(required=False, label='Cheque Number',
                                widget=forms.TextInput(attrs={'class': "form-control", 'placeholder': 'Cheque Number'}))
    payment_date = forms.DateField(label='Payment Date *',
                                   widget=forms.widgets.DateTimeInput(attrs={"type": "date", 'class': "form-control"}))
    payment_proof = forms.FileField(required=False, label='Payment Proof', widget=forms.FileInput(
        attrs={'class': "form-control", 'placeholder': 'Payment Proof', 'accept': 'application/pdf,image/*'}))

    amount = forms.DecimalField(label='Amount *', widget=forms.NumberInput(attrs={'class': "form-control"}))

    courseid = forms.MultipleChoiceField(label='Select course *', widget=forms.SelectMultiple(
        attrs={'placeholder': 'Select course', 'class': "form-control", 'size': 5}))

    def __init__(self, *args, **kwargs):
        self.student_id = kwargs.pop('student_id', None)
        print(self.student_id) 

        super(reassessment_fee_form, self).__init__(*args, **kwargs)
        student = get_object_or_404(Student, id=self.student_id)
         
        courses = Course.objects.filter(programme_id = student.programme, semester_id = student.current_sem)
        
        CHOICES = list()
        for course in courses:
            CHOICES.append((course.id, course.name))

        self.fields['courseid'].choices = CHOICES
         
    def clean(self):
        cleaned_data = super(reassessment_fee_form, self).clean()
        receipt_no = cleaned_data.get("receipt_no")
        amount = cleaned_data.get("amount")

        # check if amount is above 0
        if amount < 0:
            self.add_error('amount', "The amount should be above 0")

        # return any errors if found
        return self.cleaned_data



# from .models import Fee_Transaction

class reassessmentfee_update_Form(ModelForm):
    class Meta:
        model = reassessmentfee

        fields = ['approved', 'remarks']
        labels = {            
            'approved': 'Approved',
            'remarks': 'Remarks',            
        }

    def __init__(self, *args, **kwargs):
        
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields['remarks'].required = False        
        self.fields['approved'] = forms.ChoiceField(widget=forms.Select(attrs={'class': "form-control"}),
                                                    choices=[(1, "Yes"), (0, "No")])
    
     
class attendance_reassessment_form(ModelForm):
    class Meta:
        model = reassessmentteacher

        fields = ['attendance']
        labels = {                
            'attendance' : 'attendance'            
        }
        
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({ 'class': 'form-control' })            

    

reassessment/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from .forms import reassessment_fee_form , reassessmentfee_update_Form , attendance_reassessment_form
from .models import reassessmentfee ,reassessmentteacher
from exam_appear.models import appearance , attendance
from results.forms import MarksUpdate
from results.models import result
from course.models import Course
# Create your views here.
  


def reassessment_home(request):
    
    data = {}
    data['Courses'] = Course.objects.all()
    data['activetab'] = 'list'
    return render(request, "reassessment_home.html", data)

def reassessment_request(request):
    data ={}
    form = reassessment_fee_form(student_id = request.user.Student.id)
    reassessmentdata = reassessmentfee.objects.filter(student_id=request.user.Student.id)
    if request.method == 'POST':

        if 'submit_request' in request.POST:
            
            activetab = 'add'

            reassessment_form = reassessment_fee_form(request.POST,student_id = request.user.Student.id)
            
            
            if reassessment_form.is_valid() :                

                reassessmentfee_data = reassessmentfee()

                reassessmentfee_data.receipt_no = request.POST.get('receipt_no')
                reassessmentfee_data.payment_mode = request.POST.get('payment_mode')
                reassessmentfee_data.transaction_id = request.POST.get('transaction_id')
                reassessmentfee_data.cheque_no = request.POST.get('cheque_no')
                reassessmentfee_data.payment_date = request.POST.get('payment_date')
                if 'payment_proof' in request.FILES:
                    reassessmentfee_data.payment_proof = request.FILES['payment_proof']
                else:
                    reassessmentfee_data.payment_proof = None
                reassessmentfee_data.amount = request.POST.get('amount')
                reassessmentfee_data.student_id = request.user.Student.id
                reassessmentfee_data.courseid = request.POST.getlist('courseid')
                reassessmentfee_data.approved = 0
                reassessmentfee_data.save()
                
                activetab = 'list'

                messages.success(request,"reassessment applied successfully")

    else:
        form = reassessment_fee_form(student_id = request.user.Student.id)
        
    data["form"] = form
    data["data"] = reassessmentdata
    

    return render(request, 'requestreassessment.html', data)

def reassessment_approved(request):
    data = {}

    activetab = 'list'

    reassessmentfee_Request_data = reassessmentfee.objects.filter(approved=0)

    
    data['reassessmentfee_Request_data'] = reassessmentfee_Request_data
    
    data['activetab'] = activetab

    return render(request, 'reassessment_list.html', data)

 
def reassessment_update(request, id):
    
    reassessmentfee_Request_data = get_object_or_404(reassessmentfee, id=id)
    data = {}
    
    form = reassessmentfee_update_Form()

    if request.method == 'POST':
        form = reassessmentfee_update_Form(request.POST)
        if form.is_valid():
            #  Fee_Request.objects.get(id = request.POST.get('receipt_no'))

            approved = request.POST.get('approved', None)
            
            if int(approved) == 1:
                
                reassessmentfee_Request_data.approved = 1
                seat =  get_object_or_404(appearance, student_id=reassessmentfee_Request_data.student.id)
                
                for course in eval(reassessmentfee_Request_data.courseid):
                    reassessmentteacherdata = reassessmentteacher()
                    reassessmentteacherdata.seatno_id = seat.id
                    reassessmentteacherdata.courseid_id = int(course)
                    reassessmentteacherdata.status = 0
                    reassessmentteacherdata.save()
                
            elif int(approved) == 0:
                reassessmentfee_Request_data.approved = 2

            reassessmentfee_Request_data.remarks = request.POST.get('remarks')    
            
            reassessmentfee_Request_data.save()
            messages.success(request,"Fee status updated successfully")
            return redirect('/reassessment/list')
        # else:
        #     return redirect('/feetransaction/list')

    else:
        form = reassessmentfee_update_Form()

    data['form'] = form

    return render(request, 'update_reassessment.html', data)


def reassessment_attendance_update(request,id):
    attendance_data = get_object_or_404(reassessmentteacher, id=id)
    if request.method == 'POST':

        form = attendance_reassessment_form(request.POST)

        if form.is_valid():

            # process form data
            obj = reassessmentteacher.objects.get(id=id)  # gets new object
            obj.attendance = form.cleaned_data['attendance']
            obj.save()
            messages.success(request,"Marks updated successfully")
            return redirect('reassessment_update_attendance')

    return redirect('reassessment_update_attendance')

def reassessment_attendance_list(request):
    data = {}

    activetab = 'list'
    
    attendance_data = reassessmentteacher.objects.all()
    form = attendance_reassessment_form()
    
    data['attendance_data'] = attendance_data
    data['form'] = attendance_reassessment_form()
    data['activetab'] = activetab
    

    return render(request, 'reassessment_attendance_list.html', data)

def update_reassessment_marks(request,course_id):
    data = {}
    cur_cor = Course.objects.get(id = course_id)
    result_data = reassessmentteacher.objects.filter(courseid_id=course_id)

    marks_form = MarksUpdate(max_marks=cur_cor.max_marks)

    if request.method == 'POST':
        print(request.POST)
         
        marks_form = MarksUpdate(request.POST, max_marks=cur_cor.max_marks)
        
        if marks_form.is_valid():
            obj = reassessmentteacher.objects.get(courseid_id = course_id , seatno__seatno = request.POST.get("seat_no"))
            obj.marks = request.POST.get("marks")
            if int(request.POST.get("marks")) < int(cur_cor.pass_marks) :
                    obj.pass_fail = 0
            else :
                    obj.pass_fail = 1
            obj.save()
    else:
        marks_form = MarksUpdate(max_marks=cur_cor.max_marks)
    

    data['course'] = cur_cor
    data["result"] = result_data
    data["marks_form"] = marks_form
    return render(request, "update_reassessment_marks.html", data)

reassessment/templates/course_css_js.html
{% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/parsley.css' %}">
    <script src="{% static 'js/parsley.min.js' %}"></script>    

    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <script src="{% static 'js/sweetalert.min.js' %}"></script>    

<script>
    $(function() {
        $('#add_college').parsley();
        });



</script>

reassessment/templates/fee.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">

<script src="{% static 'js/datatablescripts.bundle.js' %}"></script>

<script>
    $(document).ready(function() {
    
      $(function () {
    $('.dataTable').DataTable();
});

        $('#id_approved').on('change', function() {
  if (this.value == "true"){
    $('#id_amount').prop('required',true);
  }
  else {
    $('#id_amount').removeAttr('required');
  }
});

        $('a[data-toggle=modal], button[data-toggle=modal]').click(function (e){
            var currentobject = $(this).attr('href');
            e.preventDefault();
           
    $('a[data-toggle=modal], button[data-toggle=modal]').click(function () {

var data_id = '';

if (typeof $(this).data('id') !== 'undefined') {

data_id = $(this).data('id');
$(".modal-body #id_receipt_no").val(data_id).change();
$(".modal-body #id_receipt_no").hide();
$("#createFormId").modal('show');
}

})
});



    });

    </script>

reassessment/templates/fee_transaction_css_js.html
{% load static %}

    <link rel="stylesheet" href="{% static 'css/parsley.css' %}">
    <script src="{% static 'js/parsley.min.js' %}"></script>    

    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <script src="{% static 'js/sweetalert.min.js' %}"></script>    



<script>
    $(function() {
        $('#student_register').parsley();

        jQuery('#id_approved_amount').prop('required',true);
        jQuery('#id_declare_semester').prop('required',true);
        jQuery('#id_remarks').removeAttr('required');  


        $('#id_approved').on('change', function() {
            if (this.value == "0"){
                jQuery('#id_approved_amount').parent(".form-group").hide();                        
                jQuery('#id_declare_semester').parent(".form-group").hide();
                jQuery('#id_approved_amount').removeAttr('required');  
                jQuery('#id_declare_semester').removeAttr('required');  
                jQuery('#id_remarks').prop('required',true);

            }
            else if(this.value == "1"){
                jQuery('#id_approved_amount').parent(".form-group").show();                        
                jQuery('#id_declare_semester').parent(".form-group").show();
                
                jQuery('#id_approved_amount').prop('required',true);
                jQuery('#id_declare_semester').prop('required',true);

                jQuery('#id_remarks').removeAttr('required');  
            }
        });
    });
</script>

reassessment/templates/reassessment_attendance_list.html
{% extends "base.html" %}

{% block content %}

    {% include 'sidebar.html' %}

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-6 col-md-8 col-sm-12">
                        <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i
                                class="fa fa-arrow-left"></i></a>reassessment Exam Attendance Attendance</h2>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html"><i class="icon-home"></i></a></li>
                            <li class="breadcrumb-item active">reassessment Exam Attendance</li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'success' %}

                            <script>
                                Notiflix.Notify.Success("{{ message }}");
                            </script>

                        {% else %}
                            <script>
                                Notiflix.Notify.Failure("{{ message }}");
                            </script>
                        {% endif %}
                    {% endfor %}

                {% endif %}

                <div class="col-lg-12 col-md-12">
                    <div class="planned_task">
                        <div class="header">
                            <ul class="nav nav-tabs-new2">


                                <li class="nav-item"><a data-toggle="tab" href="#list"
                                                        class="nav-link {% if activetab == 'list' %} active show{% endif %}">reassessment Exam
                                    Attendance</a></li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="tab-content">


                                <div class="tab-pane {% if activetab == 'list' %} active show {% endif %} " id="list">


                                    <div class="row clearfix">
                                        <div class="col-lg-12">
                                            <div class="card">
                                                <!-- <div class="header">
                                                        <h2>Table Tools<small>Basic example without any additional modification classes</small> </h2>
                                                    </div> -->
                                                <div class="body">
                                                    <table
                                                            class="table table-bordered table-striped table-hover dataTable js-exportable">
                                                        <thead>
                                                        <tr>
                                                            <th>id</th>
                                                            <th>Admission</th>
                                                            <th>Seat Number</th>
                                                            <th>Course</th>
                                                            <th>Appear</th>
                                                            <th>Action</th>
                                                        </tr>
                                                        </thead>

                                                        <tbody>

                                                        {% for data in attendance_data %}
                                                            <tr>
                                                                <td>{{ data.id }}</td>
                                                                <td>{{ data.seatno.student.admission }}</td>
                                                                <td id="seat{{ data.id }}">{{ data.seatno.seatno }}</td>
                                                                <td>{{ data.courseid_id }}</td>
                                                                <td>{{ data.attendance }}</td>
                                                                <td><a data-toggle="modal" data-id={{ data.id }}
                                                                        class="modelid btn btn-primary"
                                                                    href="#">Edit</a>
                                                                </td>
                                                            </tr>

                                                        {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>


                                <div class="modal fade" id="createFormId">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">

                                                <center>
                                                    <h3>Approved Form</h3>
                                                </center>
                                                <a href="#" class="close" data-dismiss="modal">&times;</a>
                                            </div>
                                            <div class="modal-body">


                                                <form method="post" class="form-auth-small" id="add_college"
                                                      enctype="multipart/form-data" name="updateattendance" action="/">
                                                    <p><label for="id">Id:</label>
                                                        <label for="id" id="id_id"></label>
                                                    </p>
                                                    <p><label for="seatno">Seat No:</label>
                                                        <label for="seatno" id="seatno"></label>
                                                    </p>
                                                    {% csrf_token %}
                                                    {{ form.as_p }}
                                                    <button type="submit"
                                                            class="btn btn-primary btn-lg btn-block">Submit
                                                    </button>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>


    </div>

{% endblock content %}


{% block include_page %}
    {% include 'course_css_js.html' %}
    {% include 'reassessment_attendance_list_js.html' %}
{% endblock %}

reassessment/templates/reassessment_attendance_list_js.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">

<script src="{% static 'js/datatablescripts.bundle.js' %}"></script>

<script>
  $(document).ready(function () {

    $(function () {
      $('.dataTable').DataTable();
    });


    $('a[data-toggle=modal], button[data-toggle=modal]').click(function (e){
            var currentobject = $(this).attr('href');
            e.preventDefault();
           
    $('a[data-toggle=modal], button[data-toggle=modal]').click(function () {

var data_id = '';

if (typeof $(this).data('id') !== 'undefined') {
console.log( $(this).data('id'));
data_id = $(this).data('id');
$(".modal-body #id_id").html(data_id);
$(".modal-body #seatno").html($("#seat"+data_id).html());
document.updateattendance.action= "/reassessment/" + data_id +"/update"
// $(".modal-body #id_receipt_no").hide();
$("#createFormId").modal('show');
}

})
});

  });

</script>

reassessment/templates/reassessment_css_js.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/parsley.css' %}">
<script src="{% static 'js/parsley.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
<script src="{% static 'js/sweetalert.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
<script src="{% static 'js/datatablescripts.bundle.js' %}"></script>

<script src="{% static 'js/jquery.multi-select.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/multi-select.css' %}">


<script>


    

    $(document).ready(function () {

         
        
        $('#id_courseid').multiSelect({selectableOptgroup: true, keepOrder: true});


        
    });


    $(function () {

        $('#add_college').parsley();
        

      
    });

</script>

<style>
    .college_logo {
        height: 200px;
        object-fit: scale-down;
    }
</style>

reassessment/templates/reassessment_css_js1.html
{% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/parsley.css' %}">
    <script src="{% static 'js/parsley.min.js' %}"></script>    

    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <script src="{% static 'js/sweetalert.min.js' %}"></script>    
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">

    <script src="{% static 'js/datatablescripts.bundle.js' %}"></script>
<script>
    $(function() {
        $('#add_college').parsley();
        
          
    $('.dataTable').DataTable();
        });

</script>

reassessment/templates/update_marks_css_js.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/parsley.css' %}">
<script src="{% static 'js/parsley.min.js' %}"></script>    

<script>
    $(function() {
        $('#input_marks').parsley();
    });

    $( document ).ready(function() {
        $(document).on('click','.call_marks_modal', function(){
            $('#result_id').val($(this).data('id'));
            $('#id_seat_no').val($(this).data('seatno'));
            // $('#id_marks').val($(this).data('marks'));
        });
    });
 
    

</script>



<style>
.college_logo {
    height: 200px;
    object-fit: scale-down;
}
</style>